### ISSUE TITLE
DstreamExecutionTests : Failed to create Stream from URI 

### ISSUE THREAD

**Issue by SwathiMystery** [hortonworks/dstream#188]
`DStreamExecutionTests` fails to execute all the test methods due to the following exception: 
`java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Stream from URI: file:/home/swathi/repos/myStuffs/dstream/src/test/java/io/dstream/local/ri/sample.txt`

This is due to the property file `dstream/dstream-api/src/test/resources/DStreamExecutionTests.cfg` which has the source of the pipeline as `file:${user.dir}/` which should actually be `file:${user.dir}/dstream-api/`

**Comment by olegz** [comment]
@SwathiMystery could you please describe your dev environment in a bit more details and how you are running the tests. The test doesn't fail on machine, but does on yours so something is misaligned. It has to pass on all.

**Comment by SwathiMystery** [comment]
@olegz Sure! I have raised a PR with this too. However, following is some info 
OS : Ubuntu 14.04 LTS
IDE : IntelliJ 14.0

Repo location:  `/home/swathi/repos/myStuffs/dstream`
Imported at the root level dstream. When running all tests from `/home/swathi/repos/myStuffs/dstream/dstream-api/src/test/java`, all the methods fail on `DStreamExecutionTests.java` as following

```

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Stream from URI: file:/home/swathi/repos/myStuffs/dstream/src/test/java/io/dstream/local/ri/join-hash.txt
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.dstream.local.ri.DStreamExecutionTests.joinSinglePartitionWithTransformationsAndPredicate(DStreamExecutionTests.java:642)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Stream from URI: file:/home/swathi/repos/myStuffs/dstream/src/test/java/io/dstream/local/ri/join-hash.txt
	at io.dstream.AbstractDStreamExecutionDelegate$1.call(AbstractDStreamExecutionDelegate.java:74)
	at io.dstream.AbstractDStreamExecutionDelegate$1.call(AbstractDStreamExecutionDelegate.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Failed to create Stream from URI: file:/home/swathi/repos/myStuffs/dstream/src/test/java/io/dstream/local/ri/join-hash.txt
	at io.dstream.local.ri.LocalDStreamExecutionEngine.buildStreamFromURI(LocalDStreamExecutionEngine.java:194)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at io.dstream.local.ri.LocalDStreamExecutionEngine.createInitialStream(LocalDStreamExecutionEngine.java:175)
	at io.dstream.local.ri.LocalDStreamExecutionEngine.doExecuteStage(LocalDStreamExecutionEngine.java:111)
	at io.dstream.local.ri.LocalDStreamExecutionEngine.execute(LocalDStreamExecutionEngine.java:95)
	at io.dstream.local.ri.LocalDStreamExecutionEngine.execute(LocalDStreamExecutionEngine.java:85)
	at io.dstream.local.ri.LocalDStreamExecutionDelegate.doExecute(LocalDStreamExecutionDelegate.java:60)
	at io.dstream.AbstractDStreamExecutionDelegate$1.call(AbstractDStreamExecutionDelegate.java:51)
	... 5 more
Caused by: java.nio.file.NoSuchFileException: /home/swathi/repos/myStuffs/dstream/src/test/java/io/dstream/local/ri/join-hash.txt
....

```

Please let me know if I'm missing something.
Thanks!

**Comment by olegz** [comment]
Yeah, the issue is with ```user.dir```. When running in Eclipse and/or command-line build it already points to the root of the project, but it seems like in IntelliJ it points to the root of the workspace, hence you need to add. Could you please try to run it from CLI and see if you get the same error? ```./gradlew clean :dstream-api:test```

**Comment by SwathiMystery** [comment]
It does work from command line.  But as you mentioned its an Issue with IntelliJ in reading `${user.dir}`.
Looks like the changes I suggested, makes the build fail, from command line as the root is already set.
So kindly ignore the PR.

Thanks!

**Comment by SwathiMystery** [comment]
Forgot to mention, there is a workaround to get the tests running from IntelliJ by doing the following.
`Run` > `Edit Configurations...` > `JUnit`
Click on the test package name and set `Working Directory` to `$MODULE_DIR$`

Do you think it would be a good idea to reference this in the wiki, so that IntelliJ users don't run into the issues we faced?
Thanks!

**Comment by olegz** [comment]
Definitely. Quick question though. Is there a way to make it a project wide configuration? If so we could probably make some modifications to Gradle task so it generates proper Idea files.

**Comment by SwathiMystery** [comment]
:+1: That ran through my mind as well. Let me look into it and get back to you on that.
Thanks!

**Comment by SwathiMystery** [comment]
I just wanted to confirm that the gradle generates proper idea files. I guess it was an issue with the old IDE ( IntelliJ IC-139.224.1) wherein the generated files weren't properly reflected onto the IDE settings. The new version of IDE ( IntelliJ IC-141.2735.5 ) ie. Version: 14.1.X does not face this issue as it automatically sets `$MODULE_DIR$`.

Thanks!
